Foodorama/Models/CuisineType.cs
namespace Foodorama.Models
{
    public enum CuisineType
    {
        None,
        Italian,
        French,
        German
    }
}

Foodorama/Models/Restaurant.cs
using System.ComponentModel.DataAnnotations;

namespace Foodorama.Models
{
    public class Restaurant
    {
        public int Id { get; set; }

        [Display(Name = "Restaurant Name")]
        [Required, MaxLength(80)]
        public string Name { get; set; }

        public CuisineType Cuisine { get; set; }
    }
}

Foodorama/ViewModels/HomeIndexViewModel.cs
using Foodorama.Models;
using System.Collections.Generic;

namespace Foodorama.ViewModels
{
    public class HomeIndexViewModel
    {
        public IEnumerable<Restaurant> Restaurants { get; set; }
        public string CurrentMessage { get; set; }
    }
}

Foodorama/ViewModels/RestaurantEditModel.cs
using Foodorama.Models;
using System.ComponentModel.DataAnnotations;

namespace Foodorama.ViewModels
{
    public class RestaurantEditModel
    {
        [Required, MaxLength(80)]
        public string Name { get; set; }
        public CuisineType Cuisine { get; set; }
    }
}

Foodorama/Controllers/AboutController.cs
using Microsoft.AspNetCore.Mvc;

namespace Foodorama.Controllers
{
    [Route("company/[controller]/[action]")]
    public class AboutController
    {
        public string Phone()
        {
            return "999 - 888 - 777";
        }

        public string Address()
        {
            return "USA";
        }
    }
}

Foodorama/Controllers/HomeController.cs
using Foodorama.Models;
using Foodorama.Services;
using Foodorama.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Foodorama.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        private IRestaurantData _restaurantData;
        private IGreeter _greeter;

        public HomeController(IRestaurantData restaurantData, IGreeter greeter)
        {
            _restaurantData = restaurantData;
            _greeter = greeter;
        }

        [AllowAnonymous]
        public IActionResult Index()
        {
            var model = new HomeIndexViewModel
            {
                Restaurants = _restaurantData.GetAll(),
                CurrentMessage = _greeter.GetMessageOfTheDay()
            };

            return View(model);
        }

        public IActionResult Details(int id)
        {
            var model = _restaurantData.Get(id);
            if (model == null)
            {
                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(RestaurantEditModel model)
        {
            if (ModelState.IsValid)
            {
                var newRestaurant = new Restaurant
                {
                    Name = model.Name,
                    Cuisine = model.Cuisine
                };

                newRestaurant = _restaurantData.Add(newRestaurant);

                return RedirectToAction(nameof(Details), new {id = newRestaurant});
            }
            else
            {
                return View();
            }
        }
    }
}

Foodorama/Pages/Greeting.cshtml.cs
using Foodorama.Services;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Foodorama.Pages
{
    public class GreetingModel : PageModel
    {
        private IGreeter _greeter;

        public string CurrentGreeting { get; set; }

        public GreetingModel(IGreeter greeter)
        {
            _greeter = greeter;
        }
        public void OnGet(string name)
        {
            CurrentGreeting = $"{name} : {_greeter.GetMessageOfTheDay()}";
        }
    }
}

Foodorama/Pages/Restaurants/Edit.cshtml.cs
using Foodorama.Models;
using Foodorama.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Foodorama.Pages.Restaurants
{
    [Authorize]
    public class EditModel : PageModel
    {
        private IRestaurantData _restaurantData;

        [BindProperty]
        public Restaurant Restaurant { get; set; }

        public EditModel(IRestaurantData restaurantData)
        {
            _restaurantData = restaurantData;
        }
        public IActionResult OnGet(int id)
        {
            Restaurant = _restaurantData.Get(id);
            if (Restaurant == null)
            {
                return RedirectToAction("Index", "Home");
            }
            else
            {
                return Page();
            }
        }

        public IActionResult OnPost()
        {
            if (ModelState.IsValid)
            {
                _restaurantData.Update(Restaurant);
                return RedirectToAction("Details", "Home", new {id = Restaurant.Id});
            }
            else
            {
                return Page();
            }
        }
    }
}

Foodorama/ViewComponents/GreeterViewComponent.cs
using Foodorama.Services;
using Microsoft.AspNetCore.Mvc;

namespace Foodorama.ViewComponents
{
    public class GreeterViewComponent : ViewComponent
    {
        private IGreeter _greeter;

        public GreeterViewComponent(IGreeter greeter)
        {
            _greeter = greeter;
        }

        public IViewComponentResult Invoke()
        {
            var model = _greeter.GetMessageOfTheDay();
            return View("Default", model);
        }
    }
}

Foodorama/Pages/Greeting.cshtml
@page "{name}"

@model GreetingModel

<div>@Model.CurrentGreeting</div>

Foodorama/Pages/Restaurants/Edit.cshtml
@page "{id}"
@using Foodorama.Pages.Restaurants

@model EditModel

<h1>Edit @Model.Restaurant.Name</h1>

<form method="post">
    
    <input type="hidden" asp-for="Restaurant.Id"/>

    <div>
        <label asp-for="Restaurant.Name"></label>
        <input asp-for="Restaurant.Name"/>
        <span asp-validation-for="Restaurant.Name"></span>
    </div>

    <div>
        <label asp-for="Restaurant.Cuisine">
        </label>
        <select asp-for="Restaurant.Cuisine"
                asp-items="@Html.GetEnumSelectList<CuisineType>()"></select>
        <span asp-validation-for="Restaurant.Cuisine"></span>
    </div>

    <input type="submit" name="save" value="Save"/>
</form>

Foodorama/Pages/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div>
        @RenderBody()
    </div>
<footer>
    @RenderSection("footer", required:false)
</footer>
</body>
</html>

Foodorama/Views/Home/Create.cshtml
@model Restaurant

@{
    ViewBag.Title = "Create";
}

<h1>Create</h1>

<form method="post">
    <div>
        <label asp-for="Name"></label>
        <input asp-for="Name"/>
        <span asp-validation-for="Name"></span>
    </div>
    
    <div>
        <label asp-for="Cuisine">
        </label>
        <select asp-for="Cuisine"
                asp-items="@Html.GetEnumSelectList<CuisineType>()"></select>
        <span asp-validation-for="Cuisine"></span>
    </div>

    <input type="submit" name="save" value="Save" />
</form>

Foodorama/Views/Home/Details.cshtml
@model Restaurant

@{
    ViewBag.Title = Model.Name;
}

<h1>@Model.Name</h1>

<div>
    Id: @Model.Id
</div>
<div>
    Cuisine: @Model.Cuisine
</div>

<a asp-action="Index" asp-controller="Home">Home</a>

Foodorama/Views/Home/Index.cshtml
@model HomeIndexViewModel

@{
    ViewBag.Title = "Home page";
}

<h1>All Restaurants</h1>

@foreach (var restaurant in Model.Restaurants)
{
    @Html.Partial("_Summary", restaurant)
}

<div>
    <a class="btn btn-primary" asp-action="Create">Add Restaurant</a>
</div>

Foodorama/Views/Home/_Summary.cshtml
@model Restaurant

<section class="panel panel-default">
    <h3 class="panel-heading">@Model.Name</h3>
    <div class="panel-body">
        Cuisine: @Model.Cuisine
    </div>
    <div class="panel-footer">
        <a class="btn btn-default" asp-action="Details" asp-route-id="@Model.Id">Details</a>
        <a class="btn btn-default" asp-page="/Restaurants/Edit" asp-route-id="@Model.Id">Edit</a>
    </div>
</section>

Foodorama/Views/Shared/Components/Greeter/Default.cshtml
@model string

<div>
    @Model
</div>

Foodorama/Views/Shared/Components/LoginLogout/Default.cshtml
@if (User.Identity.IsAuthenticated)
{
    <Div>Hello, @User.Identity.Name</Div>
    <a class="btn btn-default" asp-controller="Account" asp-action="Logout">Logout</a>
}
else
{
    <a class="btn btn-default" asp-controller="Account" asp-action="Login">Login</a>
}

Foodorama/Views/Shared/_Layout.cshtml
@using Foodorama.ViewComponents
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/node_modules/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
</head>
<body>
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="/">Foodorama</a>
            </div>
            <div class="navbar-right"><vc:login-logout></vc:login-logout></div>
        </div>
    </nav>
    <div class="container">
        @RenderBody()
        <footer>
            @RenderSection("footer", required: false)
            <vc:greeter></vc:greeter>
        </footer>
    </div>
    <environment include="Development">
        <script src="~/node_modules/jquery/dist/jquery.js"></script>
        <script src="~/node_modules/jquery-validation/dist/jquery.validate.js"></script>
        <script src="~/node_modules/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.js"></script>
    </environment>

    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.3.1.min.js"></script>
        <script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.17.0/jquery.validate.min.js"></script>
        <script src="https://ajax.aspnetcdn.com/ajax/jquery.validation.unobtrusive/3.2.11/jquery.validate.unobtrusive.min.js"></script>
    </environment>

</body>
</html>